# Generated by Django 3.0.3 on 2020-04-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
    ]
